"""drop unused forms and learning tables

Revision ID: 4184d91af082
Revises: c1f910612188
Create Date: 2026-08-25 14:13:36.344843

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4184d91af082'
down_revision: Union[str, None] = 'c1f910612188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - reordered so child tables drop before parents ###
    op.drop_index('ix_submission_signings_signer_id_signed_at', table_name='submission_signings')
    op.drop_index('ix_submission_signings_submission_id_signed_at', table_name='submission_signings')
    op.drop_table('submission_signings')
    op.drop_index('ix_approval_steps_assignee_id_status', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('ix_approval_actions_submission_id_created_at', table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_table('quiz_questions')
    op.drop_index('ix_quiz_sessions_user_id_created_at', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index('ix_form_submissions_owner_id_status', table_name='form_submissions')
    op.drop_index('ix_form_submissions_status_current_step_order', table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_table('form_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('SUBMIT', 'RECEIVE', 'APPROVE', 'REJECT', 'REQUEST_REVISION', 'RESUBMIT', 'SIGN', 'COMPLETE', name='ApprovalActionType'), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), autoincrement=False, nullable=True),
    sa.Column('to_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='approval_actions_actor_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name='approval_actions_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='approval_actions_pkey')
    )
    op.create_index('ix_approval_actions_submission_id_created_at', 'approval_actions', ['submission_id', 'created_at'], unique=False)
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('template_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approval_flow', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='form_templates_pkey'),
    sa.UniqueConstraint('code', name='form_templates_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_code', postgresql.ENUM('ADMIN', 'ACADEMIC_MANAGER', 'LECTURER', 'APPROVER', 'STUDENT', 'DEPARTMENT_HEAD', name='RoleCode'), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', 'SKIPPED', name='StepStatus'), autoincrement=False, nullable=False),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='approval_steps_assignee_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name='approval_steps_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='approval_steps_pkey'),
    sa.UniqueConstraint('submission_id', 'step_order', name='uq_approval_steps_submission_step_order')
    )
    op.create_index('ix_approval_steps_assignee_id_status', 'approval_steps', ['assignee_id', 'status'], unique=False)
    op.create_table('submission_signings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('signer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('signature_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hash_before', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_after', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['electronic_signatures.id'], name='submission_signings_signature_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], name='submission_signings_signer_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name='submission_signings_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submission_signings_pkey')
    )
    op.create_index('ix_submission_signings_submission_id_signed_at', 'submission_signings', ['submission_id', 'signed_at'], unique=False)
    op.create_index('ix_submission_signings_signer_id_signed_at', 'submission_signings', ['signer_id', 'signed_at'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ordinal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], name='quiz_questions_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quiz_questions_pkey'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_quiz_questions_session_ordinal')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), autoincrement=False, nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('signed_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_step_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='form_submissions_owner_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], name='form_submissions_template_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='form_submissions_pkey'),
    sa.UniqueConstraint('code', name='form_submissions_code_key')
    )
    op.create_index('ix_form_submissions_status_current_step_order', 'form_submissions', ['status', 'current_step_order'], unique=False)
    op.create_index('ix_form_submissions_owner_id_status', 'form_submissions', ['owner_id', 'status'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'SUBMITTED', name='QuizStatus'), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='quiz_sessions_course_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='quiz_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quiz_sessions_pkey')
    )
    op.create_index('ix_quiz_sessions_user_id_created_at', 'quiz_sessions', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
