"""re_add_forms_and_approvals_tables

Revision ID: 41a91c4da0e0
Revises: 4184d91af082
Create Date: 2026-08-25 14:59:19.476270

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41a91c4da0e0'
down_revision: Union[str, None] = '4184d91af082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_path', sa.String(), nullable=False),
    sa.Column('approval_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus', create_type=False), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_path', sa.String(), nullable=True),
    sa.Column('generated_hash', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_path', sa.String(), nullable=True),
    sa.Column('signed_hash', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_form_submissions_owner_id_status', 'form_submissions', ['owner_id', 'status'], unique=False)
    op.create_index('ix_form_submissions_status_current_step_order', 'form_submissions', ['status', 'current_step_order'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('SUBMIT', 'RECEIVE', 'APPROVE', 'REJECT', 'REQUEST_REVISION', 'RESUBMIT', 'SIGN', 'COMPLETE', name='ApprovalActionType', create_type=False), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('from_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus', create_type=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_actions_submission_id_created_at', 'approval_actions', ['submission_id', 'created_at'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_code', postgresql.ENUM('ADMIN', 'ACADEMIC_MANAGER', 'LECTURER', 'APPROVER', 'STUDENT', 'DEPARTMENT_HEAD', name='RoleCode', create_type=False), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', 'SKIPPED', name='StepStatus', create_type=False), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'step_order', name='uq_approval_steps_submission_step_order')
    )
    op.create_index('ix_approval_steps_assignee_id_status', 'approval_steps', ['assignee_id', 'status'], unique=False)
    op.create_table('submission_signings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('hash_before', sa.String(), nullable=False),
    sa.Column('hash_after', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['electronic_signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_signings_signer_id_signed_at', 'submission_signings', ['signer_id', 'signed_at'], unique=False)
    op.create_index('ix_submission_signings_submission_id_signed_at', 'submission_signings', ['submission_id', 'signed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_signings_submission_id_signed_at', table_name='submission_signings')
    op.drop_index('ix_submission_signings_signer_id_signed_at', table_name='submission_signings')
    op.drop_table('submission_signings')
    op.drop_index('ix_approval_steps_assignee_id_status', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('ix_approval_actions_submission_id_created_at', table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index('ix_form_submissions_status_current_step_order', table_name='form_submissions')
    op.drop_index('ix_form_submissions_owner_id_status', table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
