"""initial schema

Revision ID: c1f910612188
Revises: 
Create Date: 2026-08-25 09:51:32.501121

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f910612188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.Column('cohort_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_path', sa.String(), nullable=False),
    sa.Column('approval_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('ADMIN', 'ACADEMIC_MANAGER', 'LECTURER', 'APPROVER', 'STUDENT', 'DEPARTMENT_HEAD', name='RoleCode'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='UserStatus'), nullable=False),
    sa.Column('signature_pin_hash', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('mode', sa.Enum('QUYCHE', 'GIAOTRINH', name='ChatMode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_conversations_user_id_updated_at', 'chat_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('electronic_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_electronic_signatures_user_id_is_active', 'electronic_signatures', ['user_id', 'is_active'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_path', sa.String(), nullable=True),
    sa.Column('generated_hash', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_path', sa.String(), nullable=True),
    sa.Column('signed_hash', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_form_submissions_owner_id_status', 'form_submissions', ['owner_id', 'status'], unique=False)
    op.create_index('ix_form_submissions_status_current_step_order', 'form_submissions', ['status', 'current_step_order'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SUBMISSION_STATUS', 'SCHEDULE_CHANGE', 'DOCUMENT_INDEXED', 'SYSTEM', name='NotificationType'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link_to', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_read_at_created_at', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_user_id_revoked_at', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('enroll_year', sa.Integer(), nullable=True),
    sa.Column('cohort', sa.String(), nullable=True),
    sa.Column('training_system', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_student_profiles_class_id', 'student_profiles', ['class_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('SUBMIT', 'RECEIVE', 'APPROVE', 'REJECT', 'REQUEST_REVISION', 'RESUBMIT', 'SIGN', 'COMPLETE', name='ApprovalActionType'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_REVISION', 'REJECTED', 'APPROVED', 'COMPLETED', name='SubmissionStatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_actions_submission_id_created_at', 'approval_actions', ['submission_id', 'created_at'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_code', sa.Enum('ADMIN', 'ACADEMIC_MANAGER', 'LECTURER', 'APPROVER', 'STUDENT', 'DEPARTMENT_HEAD', name='RoleCode'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', 'SKIPPED', name='StepStatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'step_order', name='uq_approval_steps_submission_step_order')
    )
    op.create_index('ix_approval_steps_assignee_id_status', 'approval_steps', ['assignee_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='MessageRole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation_id_created_at', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('QUYCHE', 'GIAOTRINH', 'KHAC', name='DocumentType'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_document_type_course_id', 'documents', ['document_type', 'course_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('exam_format', sa.Enum('TRAC_NGHIEM', 'TU_LUAN', 'THUC_HANH', 'KET_HOP', name='ExamFormat'), nullable=False),
    sa.Column('exam_format_raw', sa.String(), nullable=True),
    sa.Column('allowed_materials', sa.String(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('chief_proctor', sa.String(), nullable=True),
    sa.Column('second_proctor', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='ExamStatus'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'semester', 'external_id', name='uq_exam_schedules_year_sem_extid')
    )
    op.create_index('ix_exam_schedules_class_id_starts_at', 'exam_schedules', ['class_id', 'starts_at'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', name='QuizStatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_sessions_user_id_created_at', 'quiz_sessions', ['user_id', 'created_at'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('instructor', sa.String(), nullable=True),
    sa.Column('delivery_mode', sa.String(), nullable=True),
    sa.Column('session_type', sa.Enum('LY_THUYET', 'THUC_HANH', 'KIEM_TRA_GIUA_KY', 'ON_TAP', 'HOC_BU', name='SessionType'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'HOLIDAY', 'COMPLETED', name='ScheduleStatus'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'semester', 'external_id', name='uq_schedules_year_sem_extid')
    )
    op.create_index('ix_schedules_class_id_starts_at', 'schedules', ['class_id', 'starts_at'], unique=False)
    op.create_index('ix_schedules_course_id_starts_at', 'schedules', ['course_id', 'starts_at'], unique=False)
    op.create_table('submission_signings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('hash_before', sa.String(), nullable=False),
    sa.Column('hash_after', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['electronic_signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_signings_signer_id_signed_at', 'submission_signings', ['signer_id', 'signed_at'], unique=False)
    op.create_index('ix_submission_signings_submission_id_signed_at', 'submission_signings', ['submission_id', 'signed_at'], unique=False)
    op.create_table('chat_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('marker', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_title', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('article_number', sa.String(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_citations_message_id', 'chat_citations', ['message_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('index_status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='IndexStatus'), nullable=False),
    sa.Column('index_error', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('contextual_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_versions_doc_version')
    )
    op.create_index('ix_document_versions_index_status', 'document_versions', ['index_status'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_quiz_questions_session_ordinal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_questions')
    op.drop_index('ix_document_versions_index_status', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_chat_citations_message_id', table_name='chat_citations')
    op.drop_table('chat_citations')
    op.drop_index('ix_submission_signings_submission_id_signed_at', table_name='submission_signings')
    op.drop_index('ix_submission_signings_signer_id_signed_at', table_name='submission_signings')
    op.drop_table('submission_signings')
    op.drop_index('ix_schedules_course_id_starts_at', table_name='schedules')
    op.drop_index('ix_schedules_class_id_starts_at', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_quiz_sessions_user_id_created_at', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index('ix_exam_schedules_class_id_starts_at', table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index('ix_documents_document_type_course_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_chat_messages_conversation_id_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_approval_steps_assignee_id_status', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('ix_approval_actions_submission_id_created_at', table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_table('user_roles')
    op.drop_index('ix_student_profiles_class_id', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('ix_refresh_tokens_user_id_revoked_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notifications_user_id_read_at_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_form_submissions_status_current_step_order', table_name='form_submissions')
    op.drop_index('ix_form_submissions_owner_id_status', table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index('ix_electronic_signatures_user_id_is_active', table_name='electronic_signatures')
    op.drop_table('electronic_signatures')
    op.drop_table('courses')
    op.drop_index('ix_chat_conversations_user_id_updated_at', table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('form_templates')
    op.drop_table('classes')
    # ### end Alembic commands ###
